### ISSUE TITLE
Set minimum PHP version in composer.json based on WordPress version

### ISSUE THREAD

**Issue by tyrann0us** [johnpbloch/build-wp#6]
As of WordPress 5.2, the system requires PHP 5.6. See https://wordpress.org/news/2019/04/minimum-php-version-update/.

It might be necessary to distinguish between WP versions so that fixes for WP <=5.1 still get `"php": ">=5.3.2"`.

Also see https://github.com/johnpbloch/wordpress/pull/43 and https://github.com/johnpbloch/wordpress-core/pull/20.

**Comment by johnpbloch** [comment]
Thanks! Just pushed out an update that will update the built package next time it runs.
